name: Automated LinkedIn Sync

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual trigger
  
jobs:
  sync-linkedin-posts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install --save-dev puppeteer-core
        # Install Chrome for Puppeteer
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        
    - name: Run LinkedIn Auto-Sync
      env:
        LINKEDIN_PROFILE_URL: https://www.linkedin.com/in/hzl
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
      run: |
        echo "🤖 Running automated LinkedIn sync..."
        node automated-linkedin-sync.js --immediate
        
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code data/ || echo "changed=true" >> $GITHUB_OUTPUT
        
    - name: Commit and push changes
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "LinkedIn Auto-Sync Bot"
        git add data/linkedin-posts.json data/linkedin-sync-info.json
        git commit -m "🤖 Auto-sync: Updated LinkedIn posts
        
        - Automated sync at $(date)
        - New posts detected and added
        - Website will auto-deploy
        
        🤖 Generated by GitHub Actions LinkedIn Auto-Sync"
        git push
        
    - name: Trigger Netlify Deploy
      if: steps.git-check.outputs.changed == 'true'
      run: |
        echo "🚀 New posts added - Netlify will auto-deploy the website"
        curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK }}
        
    - name: Summary
      run: |
        echo "✅ LinkedIn auto-sync completed!"
        echo "📊 Check https://bluehawana.com/pages/blog.html for updated posts"